# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.TextField()),
                ('IsActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesignationName', models.TextField()),
                ('IsActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.IntegerField()),
                ('Name', models.TextField()),
                ('DOB', models.DateField()),
                ('JoiningDate', models.DateField()),
                ('Email', models.TextField()),
                ('Address', models.TextField()),
                ('Mobile', models.TextField()),
                ('Gender', models.TextField()),
                ('Pincode', models.TextField()),
                ('Password', models.TextField()),
                ('ProfilePic', models.TextField()),
                ('IsActive', models.BooleanField()),
                ('IsAdmin', models.BooleanField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PES.City')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PES.Department')),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PES.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.TextField()),
                ('SkillType', models.TextField()),
                ('IsActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PES.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PES.State'),
        ),
    ]
