# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PES', '0002_auto_20170811_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desg', to='PES.Designation'),
        ),
    ]
